# docker-compose.yml

version: '3.8'
services:
  backend:
    build: ./backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
      - dbdata:/code/db
    ports:
      - 8000:8000
    env_file: .backend.env
  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file: .frontend.env
    environment:
      - HOST=0.0.0.0

volumes:
  dbdata:
